name: Deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    if: ${{ contains(github.ref, 'staging') || contains(github.ref, 'SNAPSHOT') }}
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Deployment Script
        run: bash ./scripts/deploy-pipeline.sh
        env:
          GCP_CREDENTIALS: ${{ contains(github.ref, 'staging') || secrets.GCP_CREDENTALS_HMG || secrets.GCP_CREDENTIALS_DEV }}
          COMMIT_SHA: ${{ github.sha }}
          VERSION: ${GITHUB_REF##*/}
