name: Quality Checks

on: 
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PYTHON_VERSION: '3.11'

jobs:
  install:    
    name: Install Dependencies 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --no-root 

  lint: 
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Restore Poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Run Lint
        run: poetry run make lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Restore Poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Run Tests
        run: |
          poetry run make test
          poetry run make test-coverage

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Restore Poetry
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      
      - name: Run Checks
        run: |
          poetry run make security-checks
